export const loginTypes={
  LOGIN_REQUEST:"LOGIN_REQUEST",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_FAIL:"LOGIN_FAIL",
  LOGIN_SUCCESS_GET_TOKEN:"LOGIN_SUCCESS_GET_TOKEN"
}
export const signupTypes={
  SIGNUP_REQUEST:"SIGNUP_REQUEST",
  SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
  SIGNUP_FAIL:"SIGNUP_FAIL"
}
export const logoutTypes="LOGOUT_REQUEST"
export const allPostsTypes={
  ALL_POSTS_REQUEST:"ALL_POSTS_REQUEST",
  ALL_POSTS_SUCCESS:"ALL_POSTS_SUCCESS",
  ALL_POSTS_ERROR:"ALL_POSTS_ERROR",
  ADD_MORE_POSTS:"ADD_MORE_POSTS"
}
export const categoryPostTypes={
  CATEGORY_POSTS_REQUEST:"CATEGORY_POSTS_REQUEST",
  CATEGORY_POSTS_SUCCESS:"CATEGORY_POSTS_SUCCESS",
  CATEGORY_POSTS_ERROR:"CATEGORY_POSTS_ERROR",
  ADD_MORE_POSTS:"ADD_MORE_POSTS"
}

export const authorsPostTypes={
  AUTHOR_POSTS_REQUEST:"AUTHOR_POSTS_REQUEST",
  AUTHOR_POSTS_SUCCESS:"AUTHOR_POSTS_SUCCESS",
  AUTHOR_POSTS_ERROR:"AUTHOR_POSTS_ERROR",
  ADD_MORE_POSTS:"ADD_MORE_POSTS"
}
export const myPostType={
  MY_POSTS_REQUEST:"MY_POSTS_REQUEST",
  MY_POSTS_SUCCESS:"MY_POSTS_SUCCESS",
  MY_POSTS_ERROR:"MY_POSTS_ERROR",
  ADD_NEW_POST:"ADD_NEW_POST",
  EDIT_MY_POST:"EDIT_MY_POST",
  DELETE_MY_POST:"DELETE_MY_POST"
}
